---
title: "final_project"
author: "Nicholas Huron"
date: "4/11/2018"
output: html_document
---

```{r setup, include=FALSE}
#clear workspace first
rm(list=ls())

knitr::opts_chunk$set(echo = TRUE)
#set the directory
knitr::opts_knit$set(root.dir = "/Volumes/GoogleDrive/My Drive/Global_Trait/Leiocephalus_Project/")
#For PCs
#knitr::opts_knit$set(root.dir = "G:/My Drive/")

#load required packages
library(tidyverse)
library(ieco)
library(raster)
library(rgeos)
library(rgdal)

```

#outline

##Pull and Clean Data

###Morphological Data

```{r pull in morpho dat, message = FALSE}
#read in mean morph dataset
dat.morph <- read_csv("./data/trait/Leiocephalus_sppmean_v4_4.csv", col_names = T)

##does remove scutellation counts
rm.morph <- c("16.1", "22.1", "30", "31", "32", "35", "36", "37", "15.2", "8", "10", "19.2", "19.3", "19.4", "25.2", "25.3", "25.4", "16.1", "19", "22.1", "25", "28", "29", "33", "34")
#rm the new measurements for now
rm.morph <- c(rm.morph, "14.1", "15.1")

#now make the cuts
dat.morph <- dat.morph %>%
  dplyr::select(colnames(dat.morph)[!colnames(dat.morph) %in% rm.morph]) %>%
  as_tibble(.)

#rename the species to drop the genus
#from dat.morph
knitr::kable(
dat.morph <- dat.morph %>%
  mutate(species = str_remove(species, pattern = "Leiocephalus "))
)
```

###IUCN Data
```{r pull in iucn dat, message = FALSE}
#read in iucn shorthand (will need to filter later or join appropriately)
leioiucn <- read_csv(file = "./data/iucn tabular/leiocephalus_IUCN.csv", col_names = T)
#coerce cols to be factors except species

  leioiucn <- leioiucn %>%
  mutate(island_bank = factor(island_bank),
         redlist = factor(redlist),
         notes = factor(notes)
         )

#rename the species to drop the genus
#from leioiucn (also change sci_name variable to species)
knitr::kable(
leioiucn <- leioiucn %>%
  rename(species = sci_name) %>%
  mutate(species = str_remove(species, pattern = "Leiocephalus "))
)
```

###Environmental/Spatial Data

```{r get shapefiles for species, cache=TRUE, message=FALSE}
#list of shape files for each species to cut enviro data to
leiodist <- list.files(path = "./data/distribution/Caribbean_Herp_Data/polygons/Reptiles", pattern = "^Leiocephalus.*\\.shp$", full.names = TRUE)

#test loading in the enviro data missing: TCA?
countries <- c('DOM', 'HTI', 'CUB', 'PRI', 'JAM', 'BHS', 'GLP', 'ATG', 'MTQ', 'CYM', 'TCA')

all_countries <- list()

for(a in seq_along(countries)){
  all_countries[[a]] <- getData('GADM', country = countries[a], level = 0, path = "./data/environment/")
}

comb_countries <- do.call("merge", all_countries)

comb_countries <- rbind(all_countries[[1]],
                        all_countries[[2]])

for(b in 3:length(all_countries)){
  comb_countries <- rbind(comb_countries, all_countries[[b]])
}

#writeOGR(obj = comb_countries, layer = "comb_countries", driver="ESRI Shapefile", dsn = "/Users/nicholashuron/Desktop/SRTM/")

comb_carib <- raster("/Users/nicholashuron/Desktop/SRTM/carib_v2.tif")
plot(comb_carib, col = viridis::viridis(100, direction = -1))

#some longer recoding of non-focal elevation
#comb_carib[comb_carib>=-32768 & comb_carib<=-100] <- NA
#writeRaster(comb_carib, filename="/Users/nicholashuron/Desktop/SRTM/carib_v2.1.tif", format="GTiff", overwrite=T)

comb_carib <- raster("/Users/nicholashuron/Desktop/SRTM/carib_v2.1.tif")
plot(comb_carib, col = viridis::viridis(100, direction = -1, end = 0.9, begin = 0.1))

#another way to plot
rasterVis::gplot(comb_carib, maxpixels = 5e5) + geom_tile(aes(fill = value)) + coord_equal() + viridis::scale_fill_viridis(direction = -1, end = 0.9, begin = 0.1)

#now create clippings of the raster layer for each species' shape file and extract the elevation values
#test version
plot(readOGR(leiodist[1]))
plot(crop(comb_carib,readOGR(leiodist[1])), add = T)

na.exclude(getValues(crop(comb_carib,readOGR(leiodist[1])))) %>%
  as_tibble(.) %>%
  ggplot(.) +
  geom_histogram(aes(x = value))

#now do it in a loop, storing results in a list?
leio_elev <- list()

for(b in seq_along(leiodist)){
  #populate with all values of elevation per species
  leio_elev[[b]] <- na.exclude(getValues(crop(comb_carib, readOGR(leiodist[b]))))
  
  #add in the names
  names(leio_elev)[b] <- list.files(path = "./data/distribution/Caribbean_Herp_Data/polygons/Reptiles", pattern = "^Leiocephalus.*\\.shp$", full.names = FALSE)[b]
  names(leio_elev)[b] <- gsub(pattern = ".shp", "", names(leio_elev)[b])
  
}

```

###Write a function to turn the list into a tibble where sublist names are a categorical var for each observation
```{r list to tibble function}

#list2tibble <- function(...)

#initialize output tibble
dat.tibble <- tibble(value = NA, category = NA)

for(c in seq_along(leio_elev)){
  print(c)
  unlist(leio_elev[[c]]) %>%
    bind_cols(value = ., category = names(leio_elev)[c])
}

```

##Combine Datasets and Turn Morpho Data into PCA
```{r pca}

#re-add in IUCN data
dat.morph <- right_join(leioiucn, dat.morph, by = c("species" = "species"))
colnames(dat.morph)[1] <- "species"

#log transform data and standardize by SVL
ln.dat.morph <- as.data.frame(log(dat.morph[,-1:-4]))
ln.dat.morph <- cbind(ln.dat.morph[,1], (ln.dat.morph[,-1] / ln.dat.morph[,1]))
colnames(ln.dat.morph)[1] <- "1"


#re-attach the species names
ln.dat.morph <- dat.morph %>%
  select(species:redlist) %>%
  bind_cols(., ln.dat.morph)

ln.dat.morph

#actualy PCA function
mPCA <- ln.dat.morph %>%
  select(-species:-redlist) %>%
  prcomp(center = TRUE, scale. = TRUE)

mPCA_tidy <- bind_cols(select(ln.dat.morph, species:redlist), as.data.frame(mPCA$x))
```

##Plot Datasets

###Plot PCA Data
```{r plot pca}
ggplot(data = mPCA_tidy, mapping = aes(x = PC1, y = PC2)) +
  geom_point(aes(color = species), show.legend = T)
```